#=============================================================================
#  add new config for devices check
#  add new config for factory cmdline parse
#  add new config for antenna board gpio match
#  add new config for audio match
#=============================================================================

obj-$(CONFIG_HUAWEI_DEV_SELFCHECK)        += dev_selfcheck/
obj-$(CONFIG_HUAWEI_KSTATE)               += hw_kstate/
obj-$(CONFIG_FACTORY_CMDLINE_PARSE)       += factory_cmdline_parse/
obj-$(CONFIG_ANTENNA_BOARDID_GPIO_DETECT) += antenna_board_gpio_match/
obj-$(CONFIG_HUAWEI_AUDIO)                += audio/
obj-$(CONFIG_HUAWEI_SENSORS)              += sensors/
# shell thermal config and algorithm AR000AFR67
obj-$(CONFIG_HUAWEI_THERMAL_HWNODE) += huawei_sw_thermal_node/
obj-$(CONFIG_PROC_IO_INFO)   += ioinfo/
obj-$(CONFIG_HUAWEI_SENSOR) += sensor/

